#!/bin/sh

# remove old cruft
rm -f	/etc/iftab \
	/etc/udev/networkfix.rules \
	/etc/udev/rules.d/010_networkfix.rules \
	/etc/udev/rules.d/*_persistent-net.rules

# udev can stabilize interface names on its own these days
exec /lib/udev/write_net_rules all_interfaces

