#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

# put KMS aware graphics modules into the initramfs.
for i in i915 radeon; do
	manual_add_modules ${i}
done
